package_assets: on
javascript_compressor: uglifier
compress_assets: on
gzip_assets: on
embed_assets: off

javascripts:
  lookycode:
    - public/javascripts/handlebars.js
    - public/javascripts/jquery.js
    - public/javascripts/highcharts.js
    - public/javascripts/director.js
    - public/javascripts/lookycode.js
stylesheets:
  lookycode:
    - public/stylesheets/lookycode.css
